server:
  port: 8083

spring:
  application:
    name: budget-service
  datasource:
    url: jdbc:postgresql://localhost:5432/budget-service
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

